### ISSUE TITLE
Dorothy area

### ISSUE THREAD

**Issue by RuinedKingg** [The-Plot-Twist-of-Oz/Oz_Demo#13]
It would be great if you made Dorothy's damage zone through particles and not a sprite as it is now. If you know how. I'm just not good at VFX

**Comment by markusbkk** [comment]
> It would be great if you made Dorothy's damage zone through particles and not a sprite as it is now. If you know how. I'm just not good at VFX

That's the plan. Either that or I'll make Dorothy herself a trail and the bubble into a transparent sprite, so it looks like she's floating with every move.

**Comment by markusbkk** [comment]
As discussed in the commit message, I'd like to experiment with graphical effects and really up the level of visual fidelity. Just not for this game jam.
