### ISSUE TITLE
Toxic orb spawn logic

### ISSUE THREAD

**Issue by markusbkk** [The-Plot-Twist-of-Oz/Oz_Demo#2]
Every 60 seconds, spawn an orb somewhere on the map that has to be "cleansed" by moving on top of it (if that's too easy, we might also consider having to stay over it or in the proximity of it for _n_ seconds).

If the orb isn't taken out in time, the tiles underneath it will be replaced with ones that appear withered and broken and have a green particle cloud attached to it, signifying toxicity.

If a player moves into this tarnished region, they'll instantly die.

**Comment by RuinedKingg** [comment]
Also want to do some basic logic with obrs for today. I have some concept in my mind

**Comment by markusbkk** [comment]
> Also want to do some basic logic with obrs for today. I have some concept in my mind

Awesome! Looking forward to it.

Personally, this is what I had in mind:

* A green particle orb appears in a random location on the map every 60 seconds
* The player has about 10-15 seconds to get to it (that's where Lion comes in handy, since he moves faster albeit at the expense of not dealing any damage)
* If the orb is not picked up in time, we apply some sort of filter/shader that paints the tiles around it in brown, in a cone/circle shaped fashion.
* If the player touches those brown tiles, they die instantly

**Comment by RuinedKingg** [comment]
Done. Check it

**Comment by RuinedKingg** [comment]
@markusbkk
