### ISSUE TITLE
Enemy AI.

### ISSUE THREAD

**Issue by RuinedKingg** [The-Plot-Twist-of-Oz/Oz_Demo#5]
Never too late. Issue for enemy AI changes. 

I made them follow the player and slightly reworked the spawn logic. The spawn path can be made into a separate scene and duplicated wherever we want. 

Also one problem here. Enemies slow down when approaching the player.

**Comment by markusbkk** [comment]
I actually don't mind the slowing down. Although the way this is physicality based strikes me as odd. Will have to see what it looks like once there's proper enemy sprites.

Maybe we should have both types of mobs, btw? Ones that behave like your current implementation and ones that just "wander" like before.

I think there's a typo in your references, btw. It references `res://Scene` but the folder was named `Scenes`.

**Comment by RuinedKingg** [comment]
I made 3 types of enemies based on your E1-3. 
We can make E1 follow player, E2 simply fall down and E3 fall diagonally for example

**Comment by markusbkk** [comment]
Sounds good. Let's do that.

**Comment by RuinedKingg** [comment]
Pushed update. Also changed the color of the background and added a road made of tiles. What do you think?

**Comment by markusbkk** [comment]
> Pushed update. Also changed the color of the background and added a road made of tiles. What do you think?

Looks good. Looks a bit different from what I had in mind but we can compare both our designs once I'm done with mine and figure out which one works better.

**Comment by markusbkk** [comment]
Gonna merge this in a bit, since the enemy logic seems fine and the level design is a separate issue.

**Comment by RuinedKingg** [comment]
> Looks a bit different from what I had in mind

This is not the final design. I just made some concept with what I had. The black background burned my eyes for some reasons
