### ISSUE TITLE
Character switching

### ISSUE THREAD

**Issue by markusbkk** [The-Plot-Twist-of-Oz/Oz_Demo#7]
Maybe this is something you could work on today (I really appreciate the work you've done, thus far).

The basic premise requires that the player can switch between characters with the press of a button.

What needs to change whenever the player presses a button (I'd go with the space bar, for now. On XBOX it should be the A button or right trigger, but I can implement the XBOX controller layout myself later if that's too much work. It's not really needed for the game jam but I thought it would be nice to have a build for XBOX One/Series X if we end up getting sponsorship for this game):

* Character sprite needs to be swapped
* Character abilities need to change
  * For the default character sprite, Dorothy, there needs to be a circle of AoE damage drawn around the character
  * For the Lion sprite, there needs to be no damage output but the character sprite should move twice as fast
  * For the Tin Man sprite, there needs to be an axe thrown left or right (depending on what horizontal direction the player is facing) every 1.5 seconds.
  
 If instant character swapping turns out to be too easy for the player, we could add a cool-down later but I think getting the feature in should be a priority for now.

**Comment by RuinedKingg** [comment]
Dorothy deals damage around her. Tin Man throws axes horizontally. Lion does not deal damage, but runs quickly. Do I understand correctly?

**Comment by markusbkk** [comment]
> Dorothy deals damage around her. Tin Man throws axes horizontally. Lion does not deal damage, but runs quickly. Do I understand correctly?

Correct

**Comment by RuinedKingg** [comment]
Pushed swap mechanic. You can check it. Also i have nintendo switch controller only.

**Comment by markusbkk** [comment]
Looks good.

No worries about the controller. Main target for now is the browser anyways (because that's what the game jam called for) and I have tons of controllers to test with myself.

I saw you added a timer of 5 seconds for a cool-down. I like that but I think we'll probably need a second timer for a "grace period" so that a player can swiftly swap twice before the cool down kicks in. That's for later though. Need to play-test it first. Maybe it's good the way it is.

**Comment by RuinedKingg** [comment]
Yeah. I add it cause with no cool-down that's swaps with speed of light and feels like hell to swap correctly. I put 5 sec just for test. I think 2 is the best option

**Comment by markusbkk** [comment]
True. I'll test it on my XBOX momentarily. I get a better feel there than on PC.

**Comment by RuinedKingg** [comment]
Pushed char attacks mechanics.

**Comment by RuinedKingg** [comment]
Note: My sprites are just for clarity. You can change it to yours

**Comment by markusbkk** [comment]
Will do, once I'm fully finished with the character art.

**Comment by markusbkk** [comment]
@RuinedKingg May I merge the CharacterSwap branch or are you still working on it?

**Comment by RuinedKingg** [comment]
Now you may. I add damage mechanics into this branch. It would be more correct named it CharacterAttacksAndSwap actually
