### ISSUE TITLE
Controls sub-menu scene and keyboard controls

### ISSUE THREAD

**Issue by markusbkk** [The-Plot-Twist-of-Oz/Oz_Demo#9]
I just pushed a new [branch](https://github.com/The-Plot-Twist-of-Oz/Oz_Demo/tree/ControlScheme)

Could you have a look? I'm trying to implement a proper main menu but somehow neither up/down nor my controller is reacting and nothing is ever visibly selected.

When I do pick the second option with the mouse, the controls scene pops up but is somehow displaced by one or two pixels from the top.

I also found a bug. The enemies start spawning prior to the game actually starting (before any input was ever given).

My Godot editor keeps crashing whenever I work on the scene tree, so I'll need to reboot everything and change a kernel parameter (been having weird issues ever since I upgraded to 96GB of RAM).

**Comment by RuinedKingg** [comment]
> I also found a bug. The enemies start spawning prior to the game actually starting (before any input was ever given).

I fixed it in a last commit

**Comment by markusbkk** [comment]
> > I also found a bug. The enemies start spawning prior to the game actually starting (before any input was ever given).
> 
> I fixed it in a last commit

Oh. Must've missed that. Thanks!

**Comment by RuinedKingg** [comment]
> Could you have a look? I'm trying to implement a proper main menu but somehow neither up/down nor my controller is reacting and nothing is ever visibly selected.

Lookad at this. It's work fine for me. I cant switch by buttons, but they work and controlls fine. Actually i think we should remove this button and make this hint by pick-upable book as you offered

**Comment by markusbkk** [comment]
> > Could you have a look? I'm trying to implement a proper main menu but somehow neither up/down nor my controller is reacting and nothing is ever visibly selected.
> 
> Lookad at this. It's work fine for me. I cant switch by buttons, but they work and controlls fine. Actually i think we should remove this button and make this hint by pick-upable book as you offered

The book is unrelated to this. This is for the main menu, although I get what you're saying.
I just want to make sure there's a proper main menu, with the options "New Game", "Controls" and "Credits".

BTW: I'm gonna create the credits page over my lunch break. What should I credit you as? Your username or your real name? I'm putting you as `"Code and level design: <name>"` since you did most of the code anyways.

**Comment by RuinedKingg** [comment]
Sure. You can write me as Kirill "Ken".

**Comment by RuinedKingg** [comment]
I added main menu and control scheme too
You can write control righ on a PNG or i can do it by title.
Check it
